### ISSUE TITLE
Is there any error in the provided code？

### ISSUE THREAD

**Issue by OKCup** [chenghao-ch94/DFRFS#2]
I ran pretrain.py and the code on line 160 has the following error,：
ValueError: too many values to unpack. 
I checked classifier.py and found that only one value is returned

**Comment by chenghao-ch94** [comment]
Thank you for your comments. Line 160 should only return one value. The existing version is not for this paper. I have fixed it.

**Comment by OKCup** [comment]
Thank you, it's working now.
