### ISSUE TITLE
code implementation 

### ISSUE THREAD

**Issue by 351757** [chenghao-ch94/DFRFS#3]
Dear Chenghao
I hope this message finds you well.
Thank you for sharing your code on GitHub related to your paper Disentangled Feature Representation for Few-Shot Image Classification. I have been studying your work closely, and I truly appreciate the contributions it makes to the field.
I have been inspired by the ideas presented in your paper, and I am attempting to implement them myself. However, I have encountered some difficulties.
I would like to ask if the code provided on GitHub includes the implementation of all the functionalities mentioned in the paper, or if there are some parts that have not yet been implemented. This would greatly help me understand the scope of the provided code better.
Thank you very much for your time, and I look forward to your response.

**Comment by chenghao-ch94** [comment]
Thank you for being interested in our work. To my knowledge, this code contains all the functions in the paper. Even if some parts are missing, you can easily find them from the links in the ReadMe file.

**Comment by 351757** [comment]
Thank you so much for your kind response and for providing the code. I really appreciate the effort you've put into making this work available. I will check out the links in the ReadMe file.
Wish you all the best in your studies and future research.
